version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: online
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbPass@123
      MYSQL_ROOT_PASSWORD: 123@123Aa